// <auto-generated />
using System;
using CSharpReact.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CSharpReact.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CSharpReact.Entities.Models.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b8358ff4-12ff-4b21-9128-27f11d278fb7"),
                            Body = "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
                            DateCreated = new DateTime(2022, 3, 31, 9, 39, 43, 907, DateTimeKind.Local).AddTicks(985),
                            Title = "What is Lorem Ipsum?"
                        },
                        new
                        {
                            Id = new Guid("8ec89d2d-80dd-4987-9c69-aa9e046d0cc3"),
                            Body = "Contrary to popular belief, Lorem Ipsum is not simply random text.",
                            DateCreated = new DateTime(2022, 3, 31, 9, 39, 43, 908, DateTimeKind.Local).AddTicks(5411),
                            Title = "Where does it come from?"
                        },
                        new
                        {
                            Id = new Guid("35e0d22f-2476-4336-8db7-9e082b785144"),
                            Body = "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
                            DateCreated = new DateTime(2022, 3, 31, 9, 39, 43, 908, DateTimeKind.Local).AddTicks(5430),
                            Title = "Why do we use it?"
                        },
                        new
                        {
                            Id = new Guid("3e9cb0cb-f54c-4d05-b4be-eb0d7c0e2777"),
                            Body = "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable.",
                            DateCreated = new DateTime(2022, 3, 31, 9, 39, 43, 908, DateTimeKind.Local).AddTicks(5433),
                            Title = "Where can I get some?"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
